/**
 * Generator: emits one editable React component per Lucide icon into
 * `src/generated/`, plus a re-export barrel and a manifest used by the gallery.
 *
 * Re-runnable. Bump `lucide-static` and re-run to pick up new icons.
 *
 *   bun scripts/generate.ts
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = join(root, "src", "generated");

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type IconNode = [tag: string, attrs: Record<string, string | number>];
type IconNodesFile = Record<string, IconNode[]>;

interface ManifestEntry {
  name: string;
  component: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert kebab-case-icon-name to PascalCase. */
function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

/** Stable, embeddable JSON for in-file literals. */
const j = (v: unknown): string => JSON.stringify(v);

function iconFile(componentName: string, nodes: IconNode[]): string {
  return `// AUTO-GENERATED by scripts/generate.ts - edit freely; reruns will overwrite.
"use client";
import { DrawIcon, type DrawIconProps, type IconNode } from "../engine";

const nodes: IconNode[] = ${j(nodes)};

export type ${componentName}Props = Omit<DrawIconProps, "nodes">;

export default function ${componentName}(props: ${componentName}Props) {
  return <DrawIcon nodes={nodes} {...props} />;
}
${componentName}.displayName = ${j(componentName)};
`;
}

// ---------------------------------------------------------------------------
// Pipeline
// ---------------------------------------------------------------------------

const iconNodesPath = join(
  root,
  "node_modules",
  "lucide-static",
  "icon-nodes.json"
);
const iconNodes = JSON.parse(
  readFileSync(iconNodesPath, "utf8")
) as IconNodesFile;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const indexLines: string[] = [];
const manifest: ManifestEntry[] = [];

for (const name of Object.keys(iconNodes)) {
  const component = pascal(name);
  const nodes = iconNodes[name];
  writeFileSync(join(outDir, `${name}.tsx`), iconFile(component, nodes));
  // Primary export matches Lucide's API (`Heart`), plus `Icon`-suffixed alias.
  indexLines.push(
    `export { default as ${component}, default as ${component}Icon } from "./${name}";`
  );
  manifest.push({ name, component });
}

writeFileSync(join(outDir, "index.ts"), indexLines.join("\n") + "\n");
writeFileSync(
  join(outDir, "manifest.json"),
  JSON.stringify(manifest, null, 2) + "\n"
);

console.log(`generated ${manifest.length} icons -> src/generated/`);
