/**
 * Generator: emits one editable React component per Lucide icon into
 * `src/generated/`, plus a re-export barrel and a manifest module.
 *
 * Re-runnable. Bump `lucide-static` and re-run to pick up new icons.
 *
 *   pnpm generate
 */

import {
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(__dirname, "..");
const outDir = join(pkgRoot, "src", "generated");
const signaturesDir = join(pkgRoot, "src", "modes", "signatures");
const require_ = createRequire(import.meta.url);

type IconNode = [tag: string, attrs: Record<string, string | number>];
type IconNodesFile = Record<string, IconNode[]>;
type TagsFile = Record<string, string[]>;

interface ManifestEntry {
  name: string;
  component: string;
  tags: readonly string[];
  hasSignature: boolean;
}

function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

const j = (v: unknown): string => JSON.stringify(v);

/**
 * Discovers which icons have a registered signature animation by reading the
 * filenames in `src/modes/signatures/`. A signature file named `<icon>.ts`
 * supplies the per-icon mode used when consumers pass `mode="signature"`.
 */
function loadSignatureNames(): Set<string> {
  const names = new Set<string>();
  let entries: string[];
  try {
    entries = readdirSync(signaturesDir);
  } catch {
    return names;
  }
  for (const entry of entries) {
    if (entry.endsWith(".ts") && entry !== "index.ts") {
      names.add(entry.slice(0, -3));
    }
  }
  return names;
}

function iconFile(
  componentName: string,
  name: string,
  nodes: IconNode[],
  hasSignature: boolean
): string {
  const signatureImport = hasSignature
    ? `import signature from "../modes/signatures/${name}";\n`
    : "";
  const signatureProp = hasSignature ? " signature={signature}" : "";

  // No "use client" directive here — the `tsup.config.ts` banner adds it
  // once at the top of the final bundle, so emitting it per-file just
  // bloats every module body with a duplicate string the bundler may not
  // dedupe.
  return `// AUTO-GENERATED by scripts/generate.ts - edit freely; reruns will overwrite.
import { DrawIcon, type DrawIconProps, type IconNode } from "../engine";
${signatureImport}
const nodes: IconNode[] = ${j(nodes)};

export type ${componentName}Props = Omit<DrawIconProps, "nodes" | "iconName" | "signature">;

export default function ${componentName}(props: ${componentName}Props) {
  return <DrawIcon {...props} iconName=${j(name)} nodes={nodes}${signatureProp} />;
}
${componentName}.displayName = ${j(componentName)};
`;
}

const iconNodesPath = require_.resolve("lucide-static/icon-nodes.json");
const iconNodes = JSON.parse(
  readFileSync(iconNodesPath, "utf8")
) as IconNodesFile;

const tagsPath = require_.resolve("lucide-static/tags.json");
const iconTags = JSON.parse(readFileSync(tagsPath, "utf8")) as TagsFile;

const signatureNames = loadSignatureNames();

// Overwrite in place rather than `rmSync`-ing the output directory: a wipe
// races with a concurrent `tsc` enumeration under turbo (lib typecheck
// reads src/generated while lib build's prebuild deletes it). The clean
// script still wipes everything when needed; stale `.tsx` files left
// behind by a removed-upstream icon would only surface as a typecheck
// error for code that imports the removed name, which is the correct
// behavior anyway.
mkdirSync(outDir, { recursive: true });

const indexLines: string[] = [];
const manifest: ManifestEntry[] = [];

for (const name of Object.keys(iconNodes)) {
  const component = pascal(name);
  const nodes = iconNodes[name];
  const hasSignature = signatureNames.has(name);
  writeFileSync(
    join(outDir, `${name}.tsx`),
    iconFile(component, name, nodes, hasSignature)
  );
  indexLines.push(
    `export { default as ${component}, default as ${component}Icon, type ${component}Props } from "./${name}";`
  );
  manifest.push({ name, component, tags: iconTags[name] ?? [], hasSignature });
}

writeFileSync(join(outDir, "index.ts"), indexLines.join("\n") + "\n");

// Emit manifest as a TS module with a named export. Named exports avoid
// the TS-CJS interop wart that `export default` triggers under node16
// module mode (the `missing-export-equals` rule in arethetypeswrong).
const manifestModule = `// AUTO-GENERATED by scripts/generate.ts
export interface ManifestEntry {
  name: string;
  component: string;
  tags: readonly string[];
  /**
   * True when the icon has a bespoke per-icon signature animation registered
   * under \`src/modes/signatures/\`. False means \`mode="signature"\` falls
   * back to \`mode="draw"\` at runtime. Useful for filtering UI in galleries
   * and docs sites to show only icons with completed signatures.
   */
  hasSignature: boolean;
}

export const manifest: ManifestEntry[] = ${JSON.stringify(manifest, null, 2)};
`;
writeFileSync(join(outDir, "manifest.ts"), manifestModule);

console.log(
  `generated ${manifest.length} icons (${signatureNames.size} with signatures) -> src/generated/`
);
