/**
 * Generator: emits one editable React component per Lucide icon into
 * `src/generated/`, plus a re-export barrel and a manifest module.
 *
 * Re-runnable. Bump `lucide-static` and re-run to pick up new icons.
 *
 *   pnpm generate
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(__dirname, "..");
const outDir = join(pkgRoot, "src", "generated");
const require_ = createRequire(import.meta.url);

type IconNode = [tag: string, attrs: Record<string, string | number>];
type IconNodesFile = Record<string, IconNode[]>;

interface ManifestEntry {
  name: string;
  component: string;
}

function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

const j = (v: unknown): string => JSON.stringify(v);

function iconFile(componentName: string, nodes: IconNode[]): string {
  return `// AUTO-GENERATED by scripts/generate.ts - edit freely; reruns will overwrite.
"use client";
import { DrawIcon, type DrawIconProps, type IconNode } from "../engine";

const nodes: IconNode[] = ${j(nodes)};

export type ${componentName}Props = Omit<DrawIconProps, "nodes">;

export default function ${componentName}(props: ${componentName}Props) {
  return <DrawIcon nodes={nodes} {...props} />;
}
${componentName}.displayName = ${j(componentName)};
`;
}

const iconNodesPath = require_.resolve("lucide-static/icon-nodes.json");
const iconNodes = JSON.parse(
  readFileSync(iconNodesPath, "utf8")
) as IconNodesFile;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const indexLines: string[] = [];
const manifest: ManifestEntry[] = [];

for (const name of Object.keys(iconNodes)) {
  const component = pascal(name);
  const nodes = iconNodes[name];
  writeFileSync(join(outDir, `${name}.tsx`), iconFile(component, nodes));
  indexLines.push(
    `export { default as ${component}, default as ${component}Icon } from "./${name}";`
  );
  manifest.push({ name, component });
}

writeFileSync(join(outDir, "index.ts"), indexLines.join("\n") + "\n");

// Emit manifest as a TS module so it can be a typed subpath export.
const manifestModule = `// AUTO-GENERATED by scripts/generate.ts
export interface ManifestEntry {
  name: string;
  component: string;
}

const manifest: ManifestEntry[] = ${JSON.stringify(manifest, null, 2)};

export default manifest;
`;
writeFileSync(join(outDir, "manifest.ts"), manifestModule);

console.log(`generated ${manifest.length} icons -> src/generated/`);
